/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingWebsiteRouteImport } from './routes/onboarding.website'
import { Route as OnboardingPreparingRouteImport } from './routes/onboarding.preparing'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as OnboardingCollectionsRouteImport } from './routes/onboarding.collections'
import { Route as OnboardingAnalyzingRouteImport } from './routes/onboarding.analyzing'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdminWorkspacesRouteImport } from './routes/admin.workspaces'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminIntegrationCenterRouteImport } from './routes/admin.integration-center'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminApiLogsRouteImport } from './routes/admin.api-logs'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminApiExplorerRouteImport } from './routes/admin.api-explorer'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiAssistantRouteImport } from './routes/admin.ai-assistant'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin.blogs.index'
import { Route as AdminWorkspacesIdRouteImport } from './routes/admin.workspaces.$id'
import { Route as AdminCollectionsIdRouteImport } from './routes/admin.collections.$id'
import { Route as AdminBlogsNewRouteImport } from './routes/admin.blogs.new'
import { Route as AdminBlogsIdRouteImport } from './routes/admin.blogs.$id'
import { Route as AdminBlogStatsPostIdRouteImport } from './routes/admin.blog-stats.$postId'
import { Route as AdminWorkspacesIdIndexRouteImport } from './routes/admin.workspaces.$id.index'
import { Route as AdminWorkspacesIdWebhooksRouteImport } from './routes/admin.workspaces.$id.webhooks'
import { Route as AdminWorkspacesIdUsersRouteImport } from './routes/admin.workspaces.$id.users'
import { Route as AdminWorkspacesIdSettingsRouteImport } from './routes/admin.workspaces.$id.settings'
import { Route as AdminWorkspacesIdProductsRouteImport } from './routes/admin.workspaces.$id.products'
import { Route as AdminWorkspacesIdNotificationsRouteImport } from './routes/admin.workspaces.$id.notifications'
import { Route as AdminWorkspacesIdMediaRouteImport } from './routes/admin.workspaces.$id.media'
import { Route as AdminWorkspacesIdIntegrationCenterRouteImport } from './routes/admin.workspaces.$id.integration-center'
import { Route as AdminWorkspacesIdDeveloperRouteImport } from './routes/admin.workspaces.$id.developer'
import { Route as AdminWorkspacesIdCommentsRouteImport } from './routes/admin.workspaces.$id.comments'
import { Route as AdminWorkspacesIdCollectionsRouteImport } from './routes/admin.workspaces.$id.collections'
import { Route as AdminWorkspacesIdCacheInvalidationRouteImport } from './routes/admin.workspaces.$id.cache-invalidation'
import { Route as AdminWorkspacesIdBlogsRouteImport } from './routes/admin.workspaces.$id.blogs'
import { Route as AdminWorkspacesIdArticlesRouteImport } from './routes/admin.workspaces.$id.articles'
import { Route as AdminWorkspacesIdApiKeysRouteImport } from './routes/admin.workspaces.$id.api-keys'
import { Route as AdminWorkspacesIdApiExplorerRouteImport } from './routes/admin.workspaces.$id.api-explorer'
import { Route as AdminWorkspacesIdAnalyticsRouteImport } from './routes/admin.workspaces.$id.analytics'
import { Route as AdminWorkspacesIdAiAssistantRouteImport } from './routes/admin.workspaces.$id.ai-assistant'
import { Route as AdminWorkspacesIdAboutRouteImport } from './routes/admin.workspaces.$id.about'
import { Route as AdminWorkspacesIdProductsIndexRouteImport } from './routes/admin.workspaces.$id.products.index'
import { Route as AdminWorkspacesIdNewsIndexRouteImport } from './routes/admin.workspaces.$id.news.index'
import { Route as AdminWorkspacesIdFaqsIndexRouteImport } from './routes/admin.workspaces.$id.faqs.index'
import { Route as AdminWorkspacesIdBlogsIndexRouteImport } from './routes/admin.workspaces.$id.blogs.index'
import { Route as AdminWorkspacesIdArticlesIndexRouteImport } from './routes/admin.workspaces.$id.articles.index'
import { Route as AdminWorkspacesIdProductsNewRouteImport } from './routes/admin.workspaces.$id.products.new'
import { Route as AdminWorkspacesIdProductsProductIdRouteImport } from './routes/admin.workspaces.$id.products.$productId'
import { Route as AdminWorkspacesIdNewsNewRouteImport } from './routes/admin.workspaces.$id.news.new'
import { Route as AdminWorkspacesIdNewsNewsIdRouteImport } from './routes/admin.workspaces.$id.news.$newsId'
import { Route as AdminWorkspacesIdFaqsNewRouteImport } from './routes/admin.workspaces.$id.faqs.new'
import { Route as AdminWorkspacesIdFaqsFaqIdRouteImport } from './routes/admin.workspaces.$id.faqs.$faqId'
import { Route as AdminWorkspacesIdBlogsNewRouteImport } from './routes/admin.workspaces.$id.blogs.new'
import { Route as AdminWorkspacesIdBlogsPostIdRouteImport } from './routes/admin.workspaces.$id.blogs.$postId'
import { Route as AdminWorkspacesIdArticlesNewRouteImport } from './routes/admin.workspaces.$id.articles.new'
import { Route as AdminWorkspacesIdArticlesArticleIdRouteImport } from './routes/admin.workspaces.$id.articles.$articleId'
import { Route as AdminWorkspacesIdProductsProductIdIndexRouteImport } from './routes/admin.workspaces.$id.products.$productId.index'
import { Route as AdminWorkspacesIdNewsNewsIdIndexRouteImport } from './routes/admin.workspaces.$id.news.$newsId.index'
import { Route as AdminWorkspacesIdFaqsFaqIdIndexRouteImport } from './routes/admin.workspaces.$id.faqs.$faqId.index'
import { Route as AdminWorkspacesIdBlogsPostIdIndexRouteImport } from './routes/admin.workspaces.$id.blogs.$postId.index'
import { Route as AdminWorkspacesIdArticlesArticleIdIndexRouteImport } from './routes/admin.workspaces.$id.articles.$articleId.index'
import { Route as AdminWorkspacesIdProductsProductIdEditRouteImport } from './routes/admin.workspaces.$id.products.$productId.edit'
import { Route as AdminWorkspacesIdNewsNewsIdEditRouteImport } from './routes/admin.workspaces.$id.news.$newsId.edit'
import { Route as AdminWorkspacesIdFaqsFaqIdEditRouteImport } from './routes/admin.workspaces.$id.faqs.$faqId.edit'
import { Route as AdminWorkspacesIdBlogsPostIdEditRouteImport } from './routes/admin.workspaces.$id.blogs.$postId.edit'
import { Route as AdminWorkspacesIdArticlesArticleIdEditRouteImport } from './routes/admin.workspaces.$id.articles.$articleId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWebsiteRoute = OnboardingWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPreparingRoute = OnboardingPreparingRouteImport.update({
  id: '/preparing',
  path: '/preparing',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCollectionsRoute = OnboardingCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAnalyzingRoute = OnboardingAnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => OnboardingRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationCenterRoute = AdminIntegrationCenterRouteImport.update({
  id: '/integration-center',
  path: '/integration-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiLogsRoute = AdminApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiExplorerRoute = AdminApiExplorerRouteImport.update({
  id: '/api-explorer',
  path: '/api-explorer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAssistantRoute = AdminAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesIdRoute = AdminWorkspacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminWorkspacesRoute,
} as any)
const AdminCollectionsIdRoute = AdminCollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCollectionsRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIdRoute = AdminBlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogStatsPostIdRoute = AdminBlogStatsPostIdRouteImport.update({
  id: '/blog-stats/$postId',
  path: '/blog-stats/$postId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesIdIndexRoute = AdminWorkspacesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdWebhooksRoute =
  AdminWorkspacesIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdUsersRoute = AdminWorkspacesIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdSettingsRoute =
  AdminWorkspacesIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdProductsRoute =
  AdminWorkspacesIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdNotificationsRoute =
  AdminWorkspacesIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdMediaRoute = AdminWorkspacesIdMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdIntegrationCenterRoute =
  AdminWorkspacesIdIntegrationCenterRouteImport.update({
    id: '/integration-center',
    path: '/integration-center',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdDeveloperRoute =
  AdminWorkspacesIdDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdCommentsRoute =
  AdminWorkspacesIdCommentsRouteImport.update({
    id: '/comments',
    path: '/comments',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdCollectionsRoute =
  AdminWorkspacesIdCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdCacheInvalidationRoute =
  AdminWorkspacesIdCacheInvalidationRouteImport.update({
    id: '/cache-invalidation',
    path: '/cache-invalidation',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdBlogsRoute = AdminWorkspacesIdBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdArticlesRoute =
  AdminWorkspacesIdArticlesRouteImport.update({
    id: '/articles',
    path: '/articles',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdApiKeysRoute =
  AdminWorkspacesIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdApiExplorerRoute =
  AdminWorkspacesIdApiExplorerRouteImport.update({
    id: '/api-explorer',
    path: '/api-explorer',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdAnalyticsRoute =
  AdminWorkspacesIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdAiAssistantRoute =
  AdminWorkspacesIdAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdAboutRoute = AdminWorkspacesIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdProductsIndexRoute =
  AdminWorkspacesIdProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdProductsRoute,
  } as any)
const AdminWorkspacesIdNewsIndexRoute =
  AdminWorkspacesIdNewsIndexRouteImport.update({
    id: '/news/',
    path: '/news/',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdFaqsIndexRoute =
  AdminWorkspacesIdFaqsIndexRouteImport.update({
    id: '/faqs/',
    path: '/faqs/',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdBlogsIndexRoute =
  AdminWorkspacesIdBlogsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdBlogsRoute,
  } as any)
const AdminWorkspacesIdArticlesIndexRoute =
  AdminWorkspacesIdArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdArticlesRoute,
  } as any)
const AdminWorkspacesIdProductsNewRoute =
  AdminWorkspacesIdProductsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminWorkspacesIdProductsRoute,
  } as any)
const AdminWorkspacesIdProductsProductIdRoute =
  AdminWorkspacesIdProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AdminWorkspacesIdProductsRoute,
  } as any)
const AdminWorkspacesIdNewsNewRoute =
  AdminWorkspacesIdNewsNewRouteImport.update({
    id: '/news/new',
    path: '/news/new',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdNewsNewsIdRoute =
  AdminWorkspacesIdNewsNewsIdRouteImport.update({
    id: '/news/$newsId',
    path: '/news/$newsId',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdFaqsNewRoute =
  AdminWorkspacesIdFaqsNewRouteImport.update({
    id: '/faqs/new',
    path: '/faqs/new',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdFaqsFaqIdRoute =
  AdminWorkspacesIdFaqsFaqIdRouteImport.update({
    id: '/faqs/$faqId',
    path: '/faqs/$faqId',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdBlogsNewRoute =
  AdminWorkspacesIdBlogsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminWorkspacesIdBlogsRoute,
  } as any)
const AdminWorkspacesIdBlogsPostIdRoute =
  AdminWorkspacesIdBlogsPostIdRouteImport.update({
    id: '/$postId',
    path: '/$postId',
    getParentRoute: () => AdminWorkspacesIdBlogsRoute,
  } as any)
const AdminWorkspacesIdArticlesNewRoute =
  AdminWorkspacesIdArticlesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AdminWorkspacesIdArticlesRoute,
  } as any)
const AdminWorkspacesIdArticlesArticleIdRoute =
  AdminWorkspacesIdArticlesArticleIdRouteImport.update({
    id: '/$articleId',
    path: '/$articleId',
    getParentRoute: () => AdminWorkspacesIdArticlesRoute,
  } as any)
const AdminWorkspacesIdProductsProductIdIndexRoute =
  AdminWorkspacesIdProductsProductIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdProductsProductIdRoute,
  } as any)
const AdminWorkspacesIdNewsNewsIdIndexRoute =
  AdminWorkspacesIdNewsNewsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdNewsNewsIdRoute,
  } as any)
const AdminWorkspacesIdFaqsFaqIdIndexRoute =
  AdminWorkspacesIdFaqsFaqIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdFaqsFaqIdRoute,
  } as any)
const AdminWorkspacesIdBlogsPostIdIndexRoute =
  AdminWorkspacesIdBlogsPostIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdBlogsPostIdRoute,
  } as any)
const AdminWorkspacesIdArticlesArticleIdIndexRoute =
  AdminWorkspacesIdArticlesArticleIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminWorkspacesIdArticlesArticleIdRoute,
  } as any)
const AdminWorkspacesIdProductsProductIdEditRoute =
  AdminWorkspacesIdProductsProductIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminWorkspacesIdProductsProductIdRoute,
  } as any)
const AdminWorkspacesIdNewsNewsIdEditRoute =
  AdminWorkspacesIdNewsNewsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminWorkspacesIdNewsNewsIdRoute,
  } as any)
const AdminWorkspacesIdFaqsFaqIdEditRoute =
  AdminWorkspacesIdFaqsFaqIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminWorkspacesIdFaqsFaqIdRoute,
  } as any)
const AdminWorkspacesIdBlogsPostIdEditRoute =
  AdminWorkspacesIdBlogsPostIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminWorkspacesIdBlogsPostIdRoute,
  } as any)
const AdminWorkspacesIdArticlesArticleIdEditRoute =
  AdminWorkspacesIdArticlesArticleIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminWorkspacesIdArticlesArticleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/integration-center': typeof AdminIntegrationCenterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/collections': typeof OnboardingCollectionsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/preparing': typeof OnboardingPreparingRoute
  '/onboarding/website': typeof OnboardingWebsiteRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/blog-stats/$postId': typeof AdminBlogStatsPostIdRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdRouteWithChildren
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/workspaces/$id/about': typeof AdminWorkspacesIdAboutRoute
  '/admin/workspaces/$id/ai-assistant': typeof AdminWorkspacesIdAiAssistantRoute
  '/admin/workspaces/$id/analytics': typeof AdminWorkspacesIdAnalyticsRoute
  '/admin/workspaces/$id/api-explorer': typeof AdminWorkspacesIdApiExplorerRoute
  '/admin/workspaces/$id/api-keys': typeof AdminWorkspacesIdApiKeysRoute
  '/admin/workspaces/$id/articles': typeof AdminWorkspacesIdArticlesRouteWithChildren
  '/admin/workspaces/$id/blogs': typeof AdminWorkspacesIdBlogsRouteWithChildren
  '/admin/workspaces/$id/cache-invalidation': typeof AdminWorkspacesIdCacheInvalidationRoute
  '/admin/workspaces/$id/collections': typeof AdminWorkspacesIdCollectionsRoute
  '/admin/workspaces/$id/comments': typeof AdminWorkspacesIdCommentsRoute
  '/admin/workspaces/$id/developer': typeof AdminWorkspacesIdDeveloperRoute
  '/admin/workspaces/$id/integration-center': typeof AdminWorkspacesIdIntegrationCenterRoute
  '/admin/workspaces/$id/media': typeof AdminWorkspacesIdMediaRoute
  '/admin/workspaces/$id/notifications': typeof AdminWorkspacesIdNotificationsRoute
  '/admin/workspaces/$id/products': typeof AdminWorkspacesIdProductsRouteWithChildren
  '/admin/workspaces/$id/settings': typeof AdminWorkspacesIdSettingsRoute
  '/admin/workspaces/$id/users': typeof AdminWorkspacesIdUsersRoute
  '/admin/workspaces/$id/webhooks': typeof AdminWorkspacesIdWebhooksRoute
  '/admin/workspaces/$id/': typeof AdminWorkspacesIdIndexRoute
  '/admin/workspaces/$id/articles/$articleId': typeof AdminWorkspacesIdArticlesArticleIdRouteWithChildren
  '/admin/workspaces/$id/articles/new': typeof AdminWorkspacesIdArticlesNewRoute
  '/admin/workspaces/$id/blogs/$postId': typeof AdminWorkspacesIdBlogsPostIdRouteWithChildren
  '/admin/workspaces/$id/blogs/new': typeof AdminWorkspacesIdBlogsNewRoute
  '/admin/workspaces/$id/faqs/$faqId': typeof AdminWorkspacesIdFaqsFaqIdRouteWithChildren
  '/admin/workspaces/$id/faqs/new': typeof AdminWorkspacesIdFaqsNewRoute
  '/admin/workspaces/$id/news/$newsId': typeof AdminWorkspacesIdNewsNewsIdRouteWithChildren
  '/admin/workspaces/$id/news/new': typeof AdminWorkspacesIdNewsNewRoute
  '/admin/workspaces/$id/products/$productId': typeof AdminWorkspacesIdProductsProductIdRouteWithChildren
  '/admin/workspaces/$id/products/new': typeof AdminWorkspacesIdProductsNewRoute
  '/admin/workspaces/$id/articles/': typeof AdminWorkspacesIdArticlesIndexRoute
  '/admin/workspaces/$id/blogs/': typeof AdminWorkspacesIdBlogsIndexRoute
  '/admin/workspaces/$id/faqs/': typeof AdminWorkspacesIdFaqsIndexRoute
  '/admin/workspaces/$id/news/': typeof AdminWorkspacesIdNewsIndexRoute
  '/admin/workspaces/$id/products/': typeof AdminWorkspacesIdProductsIndexRoute
  '/admin/workspaces/$id/articles/$articleId/edit': typeof AdminWorkspacesIdArticlesArticleIdEditRoute
  '/admin/workspaces/$id/blogs/$postId/edit': typeof AdminWorkspacesIdBlogsPostIdEditRoute
  '/admin/workspaces/$id/faqs/$faqId/edit': typeof AdminWorkspacesIdFaqsFaqIdEditRoute
  '/admin/workspaces/$id/news/$newsId/edit': typeof AdminWorkspacesIdNewsNewsIdEditRoute
  '/admin/workspaces/$id/products/$productId/edit': typeof AdminWorkspacesIdProductsProductIdEditRoute
  '/admin/workspaces/$id/articles/$articleId/': typeof AdminWorkspacesIdArticlesArticleIdIndexRoute
  '/admin/workspaces/$id/blogs/$postId/': typeof AdminWorkspacesIdBlogsPostIdIndexRoute
  '/admin/workspaces/$id/faqs/$faqId/': typeof AdminWorkspacesIdFaqsFaqIdIndexRoute
  '/admin/workspaces/$id/news/$newsId/': typeof AdminWorkspacesIdNewsNewsIdIndexRoute
  '/admin/workspaces/$id/products/$productId/': typeof AdminWorkspacesIdProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/integration-center': typeof AdminIntegrationCenterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/collections': typeof OnboardingCollectionsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/preparing': typeof OnboardingPreparingRoute
  '/onboarding/website': typeof OnboardingWebsiteRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/blog-stats/$postId': typeof AdminBlogStatsPostIdRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/workspaces/$id/about': typeof AdminWorkspacesIdAboutRoute
  '/admin/workspaces/$id/ai-assistant': typeof AdminWorkspacesIdAiAssistantRoute
  '/admin/workspaces/$id/analytics': typeof AdminWorkspacesIdAnalyticsRoute
  '/admin/workspaces/$id/api-explorer': typeof AdminWorkspacesIdApiExplorerRoute
  '/admin/workspaces/$id/api-keys': typeof AdminWorkspacesIdApiKeysRoute
  '/admin/workspaces/$id/cache-invalidation': typeof AdminWorkspacesIdCacheInvalidationRoute
  '/admin/workspaces/$id/collections': typeof AdminWorkspacesIdCollectionsRoute
  '/admin/workspaces/$id/comments': typeof AdminWorkspacesIdCommentsRoute
  '/admin/workspaces/$id/developer': typeof AdminWorkspacesIdDeveloperRoute
  '/admin/workspaces/$id/integration-center': typeof AdminWorkspacesIdIntegrationCenterRoute
  '/admin/workspaces/$id/media': typeof AdminWorkspacesIdMediaRoute
  '/admin/workspaces/$id/notifications': typeof AdminWorkspacesIdNotificationsRoute
  '/admin/workspaces/$id/settings': typeof AdminWorkspacesIdSettingsRoute
  '/admin/workspaces/$id/users': typeof AdminWorkspacesIdUsersRoute
  '/admin/workspaces/$id/webhooks': typeof AdminWorkspacesIdWebhooksRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdIndexRoute
  '/admin/workspaces/$id/articles/new': typeof AdminWorkspacesIdArticlesNewRoute
  '/admin/workspaces/$id/blogs/new': typeof AdminWorkspacesIdBlogsNewRoute
  '/admin/workspaces/$id/faqs/new': typeof AdminWorkspacesIdFaqsNewRoute
  '/admin/workspaces/$id/news/new': typeof AdminWorkspacesIdNewsNewRoute
  '/admin/workspaces/$id/products/new': typeof AdminWorkspacesIdProductsNewRoute
  '/admin/workspaces/$id/articles': typeof AdminWorkspacesIdArticlesIndexRoute
  '/admin/workspaces/$id/blogs': typeof AdminWorkspacesIdBlogsIndexRoute
  '/admin/workspaces/$id/faqs': typeof AdminWorkspacesIdFaqsIndexRoute
  '/admin/workspaces/$id/news': typeof AdminWorkspacesIdNewsIndexRoute
  '/admin/workspaces/$id/products': typeof AdminWorkspacesIdProductsIndexRoute
  '/admin/workspaces/$id/articles/$articleId/edit': typeof AdminWorkspacesIdArticlesArticleIdEditRoute
  '/admin/workspaces/$id/blogs/$postId/edit': typeof AdminWorkspacesIdBlogsPostIdEditRoute
  '/admin/workspaces/$id/faqs/$faqId/edit': typeof AdminWorkspacesIdFaqsFaqIdEditRoute
  '/admin/workspaces/$id/news/$newsId/edit': typeof AdminWorkspacesIdNewsNewsIdEditRoute
  '/admin/workspaces/$id/products/$productId/edit': typeof AdminWorkspacesIdProductsProductIdEditRoute
  '/admin/workspaces/$id/articles/$articleId': typeof AdminWorkspacesIdArticlesArticleIdIndexRoute
  '/admin/workspaces/$id/blogs/$postId': typeof AdminWorkspacesIdBlogsPostIdIndexRoute
  '/admin/workspaces/$id/faqs/$faqId': typeof AdminWorkspacesIdFaqsFaqIdIndexRoute
  '/admin/workspaces/$id/news/$newsId': typeof AdminWorkspacesIdNewsNewsIdIndexRoute
  '/admin/workspaces/$id/products/$productId': typeof AdminWorkspacesIdProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/integration-center': typeof AdminIntegrationCenterRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/collections': typeof OnboardingCollectionsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/preparing': typeof OnboardingPreparingRoute
  '/onboarding/website': typeof OnboardingWebsiteRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/blog-stats/$postId': typeof AdminBlogStatsPostIdRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdRouteWithChildren
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/workspaces/$id/about': typeof AdminWorkspacesIdAboutRoute
  '/admin/workspaces/$id/ai-assistant': typeof AdminWorkspacesIdAiAssistantRoute
  '/admin/workspaces/$id/analytics': typeof AdminWorkspacesIdAnalyticsRoute
  '/admin/workspaces/$id/api-explorer': typeof AdminWorkspacesIdApiExplorerRoute
  '/admin/workspaces/$id/api-keys': typeof AdminWorkspacesIdApiKeysRoute
  '/admin/workspaces/$id/articles': typeof AdminWorkspacesIdArticlesRouteWithChildren
  '/admin/workspaces/$id/blogs': typeof AdminWorkspacesIdBlogsRouteWithChildren
  '/admin/workspaces/$id/cache-invalidation': typeof AdminWorkspacesIdCacheInvalidationRoute
  '/admin/workspaces/$id/collections': typeof AdminWorkspacesIdCollectionsRoute
  '/admin/workspaces/$id/comments': typeof AdminWorkspacesIdCommentsRoute
  '/admin/workspaces/$id/developer': typeof AdminWorkspacesIdDeveloperRoute
  '/admin/workspaces/$id/integration-center': typeof AdminWorkspacesIdIntegrationCenterRoute
  '/admin/workspaces/$id/media': typeof AdminWorkspacesIdMediaRoute
  '/admin/workspaces/$id/notifications': typeof AdminWorkspacesIdNotificationsRoute
  '/admin/workspaces/$id/products': typeof AdminWorkspacesIdProductsRouteWithChildren
  '/admin/workspaces/$id/settings': typeof AdminWorkspacesIdSettingsRoute
  '/admin/workspaces/$id/users': typeof AdminWorkspacesIdUsersRoute
  '/admin/workspaces/$id/webhooks': typeof AdminWorkspacesIdWebhooksRoute
  '/admin/workspaces/$id/': typeof AdminWorkspacesIdIndexRoute
  '/admin/workspaces/$id/articles/$articleId': typeof AdminWorkspacesIdArticlesArticleIdRouteWithChildren
  '/admin/workspaces/$id/articles/new': typeof AdminWorkspacesIdArticlesNewRoute
  '/admin/workspaces/$id/blogs/$postId': typeof AdminWorkspacesIdBlogsPostIdRouteWithChildren
  '/admin/workspaces/$id/blogs/new': typeof AdminWorkspacesIdBlogsNewRoute
  '/admin/workspaces/$id/faqs/$faqId': typeof AdminWorkspacesIdFaqsFaqIdRouteWithChildren
  '/admin/workspaces/$id/faqs/new': typeof AdminWorkspacesIdFaqsNewRoute
  '/admin/workspaces/$id/news/$newsId': typeof AdminWorkspacesIdNewsNewsIdRouteWithChildren
  '/admin/workspaces/$id/news/new': typeof AdminWorkspacesIdNewsNewRoute
  '/admin/workspaces/$id/products/$productId': typeof AdminWorkspacesIdProductsProductIdRouteWithChildren
  '/admin/workspaces/$id/products/new': typeof AdminWorkspacesIdProductsNewRoute
  '/admin/workspaces/$id/articles/': typeof AdminWorkspacesIdArticlesIndexRoute
  '/admin/workspaces/$id/blogs/': typeof AdminWorkspacesIdBlogsIndexRoute
  '/admin/workspaces/$id/faqs/': typeof AdminWorkspacesIdFaqsIndexRoute
  '/admin/workspaces/$id/news/': typeof AdminWorkspacesIdNewsIndexRoute
  '/admin/workspaces/$id/products/': typeof AdminWorkspacesIdProductsIndexRoute
  '/admin/workspaces/$id/articles/$articleId/edit': typeof AdminWorkspacesIdArticlesArticleIdEditRoute
  '/admin/workspaces/$id/blogs/$postId/edit': typeof AdminWorkspacesIdBlogsPostIdEditRoute
  '/admin/workspaces/$id/faqs/$faqId/edit': typeof AdminWorkspacesIdFaqsFaqIdEditRoute
  '/admin/workspaces/$id/news/$newsId/edit': typeof AdminWorkspacesIdNewsNewsIdEditRoute
  '/admin/workspaces/$id/products/$productId/edit': typeof AdminWorkspacesIdProductsProductIdEditRoute
  '/admin/workspaces/$id/articles/$articleId/': typeof AdminWorkspacesIdArticlesArticleIdIndexRoute
  '/admin/workspaces/$id/blogs/$postId/': typeof AdminWorkspacesIdBlogsPostIdIndexRoute
  '/admin/workspaces/$id/faqs/$faqId/': typeof AdminWorkspacesIdFaqsFaqIdIndexRoute
  '/admin/workspaces/$id/news/$newsId/': typeof AdminWorkspacesIdNewsNewsIdIndexRoute
  '/admin/workspaces/$id/products/$productId/': typeof AdminWorkspacesIdProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/integration-center'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/onboarding/analyzing'
    | '/onboarding/collections'
    | '/onboarding/complete'
    | '/onboarding/preparing'
    | '/onboarding/website'
    | '/onboarding/welcome'
    | '/admin/'
    | '/blogs/'
    | '/onboarding/'
    | '/admin/blog-stats/$postId'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/workspaces/$id'
    | '/admin/blogs/'
    | '/admin/workspaces/$id/about'
    | '/admin/workspaces/$id/ai-assistant'
    | '/admin/workspaces/$id/analytics'
    | '/admin/workspaces/$id/api-explorer'
    | '/admin/workspaces/$id/api-keys'
    | '/admin/workspaces/$id/articles'
    | '/admin/workspaces/$id/blogs'
    | '/admin/workspaces/$id/cache-invalidation'
    | '/admin/workspaces/$id/collections'
    | '/admin/workspaces/$id/comments'
    | '/admin/workspaces/$id/developer'
    | '/admin/workspaces/$id/integration-center'
    | '/admin/workspaces/$id/media'
    | '/admin/workspaces/$id/notifications'
    | '/admin/workspaces/$id/products'
    | '/admin/workspaces/$id/settings'
    | '/admin/workspaces/$id/users'
    | '/admin/workspaces/$id/webhooks'
    | '/admin/workspaces/$id/'
    | '/admin/workspaces/$id/articles/$articleId'
    | '/admin/workspaces/$id/articles/new'
    | '/admin/workspaces/$id/blogs/$postId'
    | '/admin/workspaces/$id/blogs/new'
    | '/admin/workspaces/$id/faqs/$faqId'
    | '/admin/workspaces/$id/faqs/new'
    | '/admin/workspaces/$id/news/$newsId'
    | '/admin/workspaces/$id/news/new'
    | '/admin/workspaces/$id/products/$productId'
    | '/admin/workspaces/$id/products/new'
    | '/admin/workspaces/$id/articles/'
    | '/admin/workspaces/$id/blogs/'
    | '/admin/workspaces/$id/faqs/'
    | '/admin/workspaces/$id/news/'
    | '/admin/workspaces/$id/products/'
    | '/admin/workspaces/$id/articles/$articleId/edit'
    | '/admin/workspaces/$id/blogs/$postId/edit'
    | '/admin/workspaces/$id/faqs/$faqId/edit'
    | '/admin/workspaces/$id/news/$newsId/edit'
    | '/admin/workspaces/$id/products/$productId/edit'
    | '/admin/workspaces/$id/articles/$articleId/'
    | '/admin/workspaces/$id/blogs/$postId/'
    | '/admin/workspaces/$id/faqs/$faqId/'
    | '/admin/workspaces/$id/news/$newsId/'
    | '/admin/workspaces/$id/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/integration-center'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/onboarding/analyzing'
    | '/onboarding/collections'
    | '/onboarding/complete'
    | '/onboarding/preparing'
    | '/onboarding/website'
    | '/onboarding/welcome'
    | '/admin'
    | '/blogs'
    | '/onboarding'
    | '/admin/blog-stats/$postId'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/blogs'
    | '/admin/workspaces/$id/about'
    | '/admin/workspaces/$id/ai-assistant'
    | '/admin/workspaces/$id/analytics'
    | '/admin/workspaces/$id/api-explorer'
    | '/admin/workspaces/$id/api-keys'
    | '/admin/workspaces/$id/cache-invalidation'
    | '/admin/workspaces/$id/collections'
    | '/admin/workspaces/$id/comments'
    | '/admin/workspaces/$id/developer'
    | '/admin/workspaces/$id/integration-center'
    | '/admin/workspaces/$id/media'
    | '/admin/workspaces/$id/notifications'
    | '/admin/workspaces/$id/settings'
    | '/admin/workspaces/$id/users'
    | '/admin/workspaces/$id/webhooks'
    | '/admin/workspaces/$id'
    | '/admin/workspaces/$id/articles/new'
    | '/admin/workspaces/$id/blogs/new'
    | '/admin/workspaces/$id/faqs/new'
    | '/admin/workspaces/$id/news/new'
    | '/admin/workspaces/$id/products/new'
    | '/admin/workspaces/$id/articles'
    | '/admin/workspaces/$id/blogs'
    | '/admin/workspaces/$id/faqs'
    | '/admin/workspaces/$id/news'
    | '/admin/workspaces/$id/products'
    | '/admin/workspaces/$id/articles/$articleId/edit'
    | '/admin/workspaces/$id/blogs/$postId/edit'
    | '/admin/workspaces/$id/faqs/$faqId/edit'
    | '/admin/workspaces/$id/news/$newsId/edit'
    | '/admin/workspaces/$id/products/$productId/edit'
    | '/admin/workspaces/$id/articles/$articleId'
    | '/admin/workspaces/$id/blogs/$postId'
    | '/admin/workspaces/$id/faqs/$faqId'
    | '/admin/workspaces/$id/news/$newsId'
    | '/admin/workspaces/$id/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/comments'
    | '/admin/dashboard'
    | '/admin/integration-center'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/onboarding/analyzing'
    | '/onboarding/collections'
    | '/onboarding/complete'
    | '/onboarding/preparing'
    | '/onboarding/website'
    | '/onboarding/welcome'
    | '/admin/'
    | '/blogs/'
    | '/onboarding/'
    | '/admin/blog-stats/$postId'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/workspaces/$id'
    | '/admin/blogs/'
    | '/admin/workspaces/$id/about'
    | '/admin/workspaces/$id/ai-assistant'
    | '/admin/workspaces/$id/analytics'
    | '/admin/workspaces/$id/api-explorer'
    | '/admin/workspaces/$id/api-keys'
    | '/admin/workspaces/$id/articles'
    | '/admin/workspaces/$id/blogs'
    | '/admin/workspaces/$id/cache-invalidation'
    | '/admin/workspaces/$id/collections'
    | '/admin/workspaces/$id/comments'
    | '/admin/workspaces/$id/developer'
    | '/admin/workspaces/$id/integration-center'
    | '/admin/workspaces/$id/media'
    | '/admin/workspaces/$id/notifications'
    | '/admin/workspaces/$id/products'
    | '/admin/workspaces/$id/settings'
    | '/admin/workspaces/$id/users'
    | '/admin/workspaces/$id/webhooks'
    | '/admin/workspaces/$id/'
    | '/admin/workspaces/$id/articles/$articleId'
    | '/admin/workspaces/$id/articles/new'
    | '/admin/workspaces/$id/blogs/$postId'
    | '/admin/workspaces/$id/blogs/new'
    | '/admin/workspaces/$id/faqs/$faqId'
    | '/admin/workspaces/$id/faqs/new'
    | '/admin/workspaces/$id/news/$newsId'
    | '/admin/workspaces/$id/news/new'
    | '/admin/workspaces/$id/products/$productId'
    | '/admin/workspaces/$id/products/new'
    | '/admin/workspaces/$id/articles/'
    | '/admin/workspaces/$id/blogs/'
    | '/admin/workspaces/$id/faqs/'
    | '/admin/workspaces/$id/news/'
    | '/admin/workspaces/$id/products/'
    | '/admin/workspaces/$id/articles/$articleId/edit'
    | '/admin/workspaces/$id/blogs/$postId/edit'
    | '/admin/workspaces/$id/faqs/$faqId/edit'
    | '/admin/workspaces/$id/news/$newsId/edit'
    | '/admin/workspaces/$id/products/$productId/edit'
    | '/admin/workspaces/$id/articles/$articleId/'
    | '/admin/workspaces/$id/blogs/$postId/'
    | '/admin/workspaces/$id/faqs/$faqId/'
    | '/admin/workspaces/$id/news/$newsId/'
    | '/admin/workspaces/$id/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignupRoute: typeof SignupRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/website': {
      id: '/onboarding/website'
      path: '/website'
      fullPath: '/onboarding/website'
      preLoaderRoute: typeof OnboardingWebsiteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/preparing': {
      id: '/onboarding/preparing'
      path: '/preparing'
      fullPath: '/onboarding/preparing'
      preLoaderRoute: typeof OnboardingPreparingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/collections': {
      id: '/onboarding/collections'
      path: '/collections'
      fullPath: '/onboarding/collections'
      preLoaderRoute: typeof OnboardingCollectionsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/analyzing': {
      id: '/onboarding/analyzing'
      path: '/analyzing'
      fullPath: '/onboarding/analyzing'
      preLoaderRoute: typeof OnboardingAnalyzingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integration-center': {
      id: '/admin/integration-center'
      path: '/integration-center'
      fullPath: '/admin/integration-center'
      preLoaderRoute: typeof AdminIntegrationCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-logs': {
      id: '/admin/api-logs'
      path: '/api-logs'
      fullPath: '/admin/api-logs'
      preLoaderRoute: typeof AdminApiLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-explorer': {
      id: '/admin/api-explorer'
      path: '/api-explorer'
      fullPath: '/admin/api-explorer'
      preLoaderRoute: typeof AdminApiExplorerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-assistant': {
      id: '/admin/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/admin/ai-assistant'
      preLoaderRoute: typeof AdminAiAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces/$id': {
      id: '/admin/workspaces/$id'
      path: '/$id'
      fullPath: '/admin/workspaces/$id'
      preLoaderRoute: typeof AdminWorkspacesIdRouteImport
      parentRoute: typeof AdminWorkspacesRoute
    }
    '/admin/collections/$id': {
      id: '/admin/collections/$id'
      path: '/$id'
      fullPath: '/admin/collections/$id'
      preLoaderRoute: typeof AdminCollectionsIdRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/$id': {
      id: '/admin/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminBlogsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-stats/$postId': {
      id: '/admin/blog-stats/$postId'
      path: '/blog-stats/$postId'
      fullPath: '/admin/blog-stats/$postId'
      preLoaderRoute: typeof AdminBlogStatsPostIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces/$id/': {
      id: '/admin/workspaces/$id/'
      path: '/'
      fullPath: '/admin/workspaces/$id/'
      preLoaderRoute: typeof AdminWorkspacesIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/webhooks': {
      id: '/admin/workspaces/$id/webhooks'
      path: '/webhooks'
      fullPath: '/admin/workspaces/$id/webhooks'
      preLoaderRoute: typeof AdminWorkspacesIdWebhooksRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/users': {
      id: '/admin/workspaces/$id/users'
      path: '/users'
      fullPath: '/admin/workspaces/$id/users'
      preLoaderRoute: typeof AdminWorkspacesIdUsersRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/settings': {
      id: '/admin/workspaces/$id/settings'
      path: '/settings'
      fullPath: '/admin/workspaces/$id/settings'
      preLoaderRoute: typeof AdminWorkspacesIdSettingsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/products': {
      id: '/admin/workspaces/$id/products'
      path: '/products'
      fullPath: '/admin/workspaces/$id/products'
      preLoaderRoute: typeof AdminWorkspacesIdProductsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/notifications': {
      id: '/admin/workspaces/$id/notifications'
      path: '/notifications'
      fullPath: '/admin/workspaces/$id/notifications'
      preLoaderRoute: typeof AdminWorkspacesIdNotificationsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/media': {
      id: '/admin/workspaces/$id/media'
      path: '/media'
      fullPath: '/admin/workspaces/$id/media'
      preLoaderRoute: typeof AdminWorkspacesIdMediaRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/integration-center': {
      id: '/admin/workspaces/$id/integration-center'
      path: '/integration-center'
      fullPath: '/admin/workspaces/$id/integration-center'
      preLoaderRoute: typeof AdminWorkspacesIdIntegrationCenterRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/developer': {
      id: '/admin/workspaces/$id/developer'
      path: '/developer'
      fullPath: '/admin/workspaces/$id/developer'
      preLoaderRoute: typeof AdminWorkspacesIdDeveloperRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/comments': {
      id: '/admin/workspaces/$id/comments'
      path: '/comments'
      fullPath: '/admin/workspaces/$id/comments'
      preLoaderRoute: typeof AdminWorkspacesIdCommentsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/collections': {
      id: '/admin/workspaces/$id/collections'
      path: '/collections'
      fullPath: '/admin/workspaces/$id/collections'
      preLoaderRoute: typeof AdminWorkspacesIdCollectionsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/cache-invalidation': {
      id: '/admin/workspaces/$id/cache-invalidation'
      path: '/cache-invalidation'
      fullPath: '/admin/workspaces/$id/cache-invalidation'
      preLoaderRoute: typeof AdminWorkspacesIdCacheInvalidationRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/blogs': {
      id: '/admin/workspaces/$id/blogs'
      path: '/blogs'
      fullPath: '/admin/workspaces/$id/blogs'
      preLoaderRoute: typeof AdminWorkspacesIdBlogsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/articles': {
      id: '/admin/workspaces/$id/articles'
      path: '/articles'
      fullPath: '/admin/workspaces/$id/articles'
      preLoaderRoute: typeof AdminWorkspacesIdArticlesRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/api-keys': {
      id: '/admin/workspaces/$id/api-keys'
      path: '/api-keys'
      fullPath: '/admin/workspaces/$id/api-keys'
      preLoaderRoute: typeof AdminWorkspacesIdApiKeysRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/api-explorer': {
      id: '/admin/workspaces/$id/api-explorer'
      path: '/api-explorer'
      fullPath: '/admin/workspaces/$id/api-explorer'
      preLoaderRoute: typeof AdminWorkspacesIdApiExplorerRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/analytics': {
      id: '/admin/workspaces/$id/analytics'
      path: '/analytics'
      fullPath: '/admin/workspaces/$id/analytics'
      preLoaderRoute: typeof AdminWorkspacesIdAnalyticsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/ai-assistant': {
      id: '/admin/workspaces/$id/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/admin/workspaces/$id/ai-assistant'
      preLoaderRoute: typeof AdminWorkspacesIdAiAssistantRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/about': {
      id: '/admin/workspaces/$id/about'
      path: '/about'
      fullPath: '/admin/workspaces/$id/about'
      preLoaderRoute: typeof AdminWorkspacesIdAboutRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/products/': {
      id: '/admin/workspaces/$id/products/'
      path: '/'
      fullPath: '/admin/workspaces/$id/products/'
      preLoaderRoute: typeof AdminWorkspacesIdProductsIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdProductsRoute
    }
    '/admin/workspaces/$id/news/': {
      id: '/admin/workspaces/$id/news/'
      path: '/news'
      fullPath: '/admin/workspaces/$id/news/'
      preLoaderRoute: typeof AdminWorkspacesIdNewsIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/faqs/': {
      id: '/admin/workspaces/$id/faqs/'
      path: '/faqs'
      fullPath: '/admin/workspaces/$id/faqs/'
      preLoaderRoute: typeof AdminWorkspacesIdFaqsIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/blogs/': {
      id: '/admin/workspaces/$id/blogs/'
      path: '/'
      fullPath: '/admin/workspaces/$id/blogs/'
      preLoaderRoute: typeof AdminWorkspacesIdBlogsIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdBlogsRoute
    }
    '/admin/workspaces/$id/articles/': {
      id: '/admin/workspaces/$id/articles/'
      path: '/'
      fullPath: '/admin/workspaces/$id/articles/'
      preLoaderRoute: typeof AdminWorkspacesIdArticlesIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdArticlesRoute
    }
    '/admin/workspaces/$id/products/new': {
      id: '/admin/workspaces/$id/products/new'
      path: '/new'
      fullPath: '/admin/workspaces/$id/products/new'
      preLoaderRoute: typeof AdminWorkspacesIdProductsNewRouteImport
      parentRoute: typeof AdminWorkspacesIdProductsRoute
    }
    '/admin/workspaces/$id/products/$productId': {
      id: '/admin/workspaces/$id/products/$productId'
      path: '/$productId'
      fullPath: '/admin/workspaces/$id/products/$productId'
      preLoaderRoute: typeof AdminWorkspacesIdProductsProductIdRouteImport
      parentRoute: typeof AdminWorkspacesIdProductsRoute
    }
    '/admin/workspaces/$id/news/new': {
      id: '/admin/workspaces/$id/news/new'
      path: '/news/new'
      fullPath: '/admin/workspaces/$id/news/new'
      preLoaderRoute: typeof AdminWorkspacesIdNewsNewRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/news/$newsId': {
      id: '/admin/workspaces/$id/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/admin/workspaces/$id/news/$newsId'
      preLoaderRoute: typeof AdminWorkspacesIdNewsNewsIdRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/faqs/new': {
      id: '/admin/workspaces/$id/faqs/new'
      path: '/faqs/new'
      fullPath: '/admin/workspaces/$id/faqs/new'
      preLoaderRoute: typeof AdminWorkspacesIdFaqsNewRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/faqs/$faqId': {
      id: '/admin/workspaces/$id/faqs/$faqId'
      path: '/faqs/$faqId'
      fullPath: '/admin/workspaces/$id/faqs/$faqId'
      preLoaderRoute: typeof AdminWorkspacesIdFaqsFaqIdRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/blogs/new': {
      id: '/admin/workspaces/$id/blogs/new'
      path: '/new'
      fullPath: '/admin/workspaces/$id/blogs/new'
      preLoaderRoute: typeof AdminWorkspacesIdBlogsNewRouteImport
      parentRoute: typeof AdminWorkspacesIdBlogsRoute
    }
    '/admin/workspaces/$id/blogs/$postId': {
      id: '/admin/workspaces/$id/blogs/$postId'
      path: '/$postId'
      fullPath: '/admin/workspaces/$id/blogs/$postId'
      preLoaderRoute: typeof AdminWorkspacesIdBlogsPostIdRouteImport
      parentRoute: typeof AdminWorkspacesIdBlogsRoute
    }
    '/admin/workspaces/$id/articles/new': {
      id: '/admin/workspaces/$id/articles/new'
      path: '/new'
      fullPath: '/admin/workspaces/$id/articles/new'
      preLoaderRoute: typeof AdminWorkspacesIdArticlesNewRouteImport
      parentRoute: typeof AdminWorkspacesIdArticlesRoute
    }
    '/admin/workspaces/$id/articles/$articleId': {
      id: '/admin/workspaces/$id/articles/$articleId'
      path: '/$articleId'
      fullPath: '/admin/workspaces/$id/articles/$articleId'
      preLoaderRoute: typeof AdminWorkspacesIdArticlesArticleIdRouteImport
      parentRoute: typeof AdminWorkspacesIdArticlesRoute
    }
    '/admin/workspaces/$id/products/$productId/': {
      id: '/admin/workspaces/$id/products/$productId/'
      path: '/'
      fullPath: '/admin/workspaces/$id/products/$productId/'
      preLoaderRoute: typeof AdminWorkspacesIdProductsProductIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdProductsProductIdRoute
    }
    '/admin/workspaces/$id/news/$newsId/': {
      id: '/admin/workspaces/$id/news/$newsId/'
      path: '/'
      fullPath: '/admin/workspaces/$id/news/$newsId/'
      preLoaderRoute: typeof AdminWorkspacesIdNewsNewsIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdNewsNewsIdRoute
    }
    '/admin/workspaces/$id/faqs/$faqId/': {
      id: '/admin/workspaces/$id/faqs/$faqId/'
      path: '/'
      fullPath: '/admin/workspaces/$id/faqs/$faqId/'
      preLoaderRoute: typeof AdminWorkspacesIdFaqsFaqIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdFaqsFaqIdRoute
    }
    '/admin/workspaces/$id/blogs/$postId/': {
      id: '/admin/workspaces/$id/blogs/$postId/'
      path: '/'
      fullPath: '/admin/workspaces/$id/blogs/$postId/'
      preLoaderRoute: typeof AdminWorkspacesIdBlogsPostIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdBlogsPostIdRoute
    }
    '/admin/workspaces/$id/articles/$articleId/': {
      id: '/admin/workspaces/$id/articles/$articleId/'
      path: '/'
      fullPath: '/admin/workspaces/$id/articles/$articleId/'
      preLoaderRoute: typeof AdminWorkspacesIdArticlesArticleIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdArticlesArticleIdRoute
    }
    '/admin/workspaces/$id/products/$productId/edit': {
      id: '/admin/workspaces/$id/products/$productId/edit'
      path: '/edit'
      fullPath: '/admin/workspaces/$id/products/$productId/edit'
      preLoaderRoute: typeof AdminWorkspacesIdProductsProductIdEditRouteImport
      parentRoute: typeof AdminWorkspacesIdProductsProductIdRoute
    }
    '/admin/workspaces/$id/news/$newsId/edit': {
      id: '/admin/workspaces/$id/news/$newsId/edit'
      path: '/edit'
      fullPath: '/admin/workspaces/$id/news/$newsId/edit'
      preLoaderRoute: typeof AdminWorkspacesIdNewsNewsIdEditRouteImport
      parentRoute: typeof AdminWorkspacesIdNewsNewsIdRoute
    }
    '/admin/workspaces/$id/faqs/$faqId/edit': {
      id: '/admin/workspaces/$id/faqs/$faqId/edit'
      path: '/edit'
      fullPath: '/admin/workspaces/$id/faqs/$faqId/edit'
      preLoaderRoute: typeof AdminWorkspacesIdFaqsFaqIdEditRouteImport
      parentRoute: typeof AdminWorkspacesIdFaqsFaqIdRoute
    }
    '/admin/workspaces/$id/blogs/$postId/edit': {
      id: '/admin/workspaces/$id/blogs/$postId/edit'
      path: '/edit'
      fullPath: '/admin/workspaces/$id/blogs/$postId/edit'
      preLoaderRoute: typeof AdminWorkspacesIdBlogsPostIdEditRouteImport
      parentRoute: typeof AdminWorkspacesIdBlogsPostIdRoute
    }
    '/admin/workspaces/$id/articles/$articleId/edit': {
      id: '/admin/workspaces/$id/articles/$articleId/edit'
      path: '/edit'
      fullPath: '/admin/workspaces/$id/articles/$articleId/edit'
      preLoaderRoute: typeof AdminWorkspacesIdArticlesArticleIdEditRouteImport
      parentRoute: typeof AdminWorkspacesIdArticlesArticleIdRoute
    }
  }
}

interface AdminCollectionsRouteChildren {
  AdminCollectionsIdRoute: typeof AdminCollectionsIdRoute
}

const AdminCollectionsRouteChildren: AdminCollectionsRouteChildren = {
  AdminCollectionsIdRoute: AdminCollectionsIdRoute,
}

const AdminCollectionsRouteWithChildren =
  AdminCollectionsRoute._addFileChildren(AdminCollectionsRouteChildren)

interface AdminWorkspacesIdArticlesArticleIdRouteChildren {
  AdminWorkspacesIdArticlesArticleIdEditRoute: typeof AdminWorkspacesIdArticlesArticleIdEditRoute
  AdminWorkspacesIdArticlesArticleIdIndexRoute: typeof AdminWorkspacesIdArticlesArticleIdIndexRoute
}

const AdminWorkspacesIdArticlesArticleIdRouteChildren: AdminWorkspacesIdArticlesArticleIdRouteChildren =
  {
    AdminWorkspacesIdArticlesArticleIdEditRoute:
      AdminWorkspacesIdArticlesArticleIdEditRoute,
    AdminWorkspacesIdArticlesArticleIdIndexRoute:
      AdminWorkspacesIdArticlesArticleIdIndexRoute,
  }

const AdminWorkspacesIdArticlesArticleIdRouteWithChildren =
  AdminWorkspacesIdArticlesArticleIdRoute._addFileChildren(
    AdminWorkspacesIdArticlesArticleIdRouteChildren,
  )

interface AdminWorkspacesIdArticlesRouteChildren {
  AdminWorkspacesIdArticlesArticleIdRoute: typeof AdminWorkspacesIdArticlesArticleIdRouteWithChildren
  AdminWorkspacesIdArticlesNewRoute: typeof AdminWorkspacesIdArticlesNewRoute
  AdminWorkspacesIdArticlesIndexRoute: typeof AdminWorkspacesIdArticlesIndexRoute
}

const AdminWorkspacesIdArticlesRouteChildren: AdminWorkspacesIdArticlesRouteChildren =
  {
    AdminWorkspacesIdArticlesArticleIdRoute:
      AdminWorkspacesIdArticlesArticleIdRouteWithChildren,
    AdminWorkspacesIdArticlesNewRoute: AdminWorkspacesIdArticlesNewRoute,
    AdminWorkspacesIdArticlesIndexRoute: AdminWorkspacesIdArticlesIndexRoute,
  }

const AdminWorkspacesIdArticlesRouteWithChildren =
  AdminWorkspacesIdArticlesRoute._addFileChildren(
    AdminWorkspacesIdArticlesRouteChildren,
  )

interface AdminWorkspacesIdBlogsPostIdRouteChildren {
  AdminWorkspacesIdBlogsPostIdEditRoute: typeof AdminWorkspacesIdBlogsPostIdEditRoute
  AdminWorkspacesIdBlogsPostIdIndexRoute: typeof AdminWorkspacesIdBlogsPostIdIndexRoute
}

const AdminWorkspacesIdBlogsPostIdRouteChildren: AdminWorkspacesIdBlogsPostIdRouteChildren =
  {
    AdminWorkspacesIdBlogsPostIdEditRoute:
      AdminWorkspacesIdBlogsPostIdEditRoute,
    AdminWorkspacesIdBlogsPostIdIndexRoute:
      AdminWorkspacesIdBlogsPostIdIndexRoute,
  }

const AdminWorkspacesIdBlogsPostIdRouteWithChildren =
  AdminWorkspacesIdBlogsPostIdRoute._addFileChildren(
    AdminWorkspacesIdBlogsPostIdRouteChildren,
  )

interface AdminWorkspacesIdBlogsRouteChildren {
  AdminWorkspacesIdBlogsPostIdRoute: typeof AdminWorkspacesIdBlogsPostIdRouteWithChildren
  AdminWorkspacesIdBlogsNewRoute: typeof AdminWorkspacesIdBlogsNewRoute
  AdminWorkspacesIdBlogsIndexRoute: typeof AdminWorkspacesIdBlogsIndexRoute
}

const AdminWorkspacesIdBlogsRouteChildren: AdminWorkspacesIdBlogsRouteChildren =
  {
    AdminWorkspacesIdBlogsPostIdRoute:
      AdminWorkspacesIdBlogsPostIdRouteWithChildren,
    AdminWorkspacesIdBlogsNewRoute: AdminWorkspacesIdBlogsNewRoute,
    AdminWorkspacesIdBlogsIndexRoute: AdminWorkspacesIdBlogsIndexRoute,
  }

const AdminWorkspacesIdBlogsRouteWithChildren =
  AdminWorkspacesIdBlogsRoute._addFileChildren(
    AdminWorkspacesIdBlogsRouteChildren,
  )

interface AdminWorkspacesIdProductsProductIdRouteChildren {
  AdminWorkspacesIdProductsProductIdEditRoute: typeof AdminWorkspacesIdProductsProductIdEditRoute
  AdminWorkspacesIdProductsProductIdIndexRoute: typeof AdminWorkspacesIdProductsProductIdIndexRoute
}

const AdminWorkspacesIdProductsProductIdRouteChildren: AdminWorkspacesIdProductsProductIdRouteChildren =
  {
    AdminWorkspacesIdProductsProductIdEditRoute:
      AdminWorkspacesIdProductsProductIdEditRoute,
    AdminWorkspacesIdProductsProductIdIndexRoute:
      AdminWorkspacesIdProductsProductIdIndexRoute,
  }

const AdminWorkspacesIdProductsProductIdRouteWithChildren =
  AdminWorkspacesIdProductsProductIdRoute._addFileChildren(
    AdminWorkspacesIdProductsProductIdRouteChildren,
  )

interface AdminWorkspacesIdProductsRouteChildren {
  AdminWorkspacesIdProductsProductIdRoute: typeof AdminWorkspacesIdProductsProductIdRouteWithChildren
  AdminWorkspacesIdProductsNewRoute: typeof AdminWorkspacesIdProductsNewRoute
  AdminWorkspacesIdProductsIndexRoute: typeof AdminWorkspacesIdProductsIndexRoute
}

const AdminWorkspacesIdProductsRouteChildren: AdminWorkspacesIdProductsRouteChildren =
  {
    AdminWorkspacesIdProductsProductIdRoute:
      AdminWorkspacesIdProductsProductIdRouteWithChildren,
    AdminWorkspacesIdProductsNewRoute: AdminWorkspacesIdProductsNewRoute,
    AdminWorkspacesIdProductsIndexRoute: AdminWorkspacesIdProductsIndexRoute,
  }

const AdminWorkspacesIdProductsRouteWithChildren =
  AdminWorkspacesIdProductsRoute._addFileChildren(
    AdminWorkspacesIdProductsRouteChildren,
  )

interface AdminWorkspacesIdFaqsFaqIdRouteChildren {
  AdminWorkspacesIdFaqsFaqIdEditRoute: typeof AdminWorkspacesIdFaqsFaqIdEditRoute
  AdminWorkspacesIdFaqsFaqIdIndexRoute: typeof AdminWorkspacesIdFaqsFaqIdIndexRoute
}

const AdminWorkspacesIdFaqsFaqIdRouteChildren: AdminWorkspacesIdFaqsFaqIdRouteChildren =
  {
    AdminWorkspacesIdFaqsFaqIdEditRoute: AdminWorkspacesIdFaqsFaqIdEditRoute,
    AdminWorkspacesIdFaqsFaqIdIndexRoute: AdminWorkspacesIdFaqsFaqIdIndexRoute,
  }

const AdminWorkspacesIdFaqsFaqIdRouteWithChildren =
  AdminWorkspacesIdFaqsFaqIdRoute._addFileChildren(
    AdminWorkspacesIdFaqsFaqIdRouteChildren,
  )

interface AdminWorkspacesIdNewsNewsIdRouteChildren {
  AdminWorkspacesIdNewsNewsIdEditRoute: typeof AdminWorkspacesIdNewsNewsIdEditRoute
  AdminWorkspacesIdNewsNewsIdIndexRoute: typeof AdminWorkspacesIdNewsNewsIdIndexRoute
}

const AdminWorkspacesIdNewsNewsIdRouteChildren: AdminWorkspacesIdNewsNewsIdRouteChildren =
  {
    AdminWorkspacesIdNewsNewsIdEditRoute: AdminWorkspacesIdNewsNewsIdEditRoute,
    AdminWorkspacesIdNewsNewsIdIndexRoute:
      AdminWorkspacesIdNewsNewsIdIndexRoute,
  }

const AdminWorkspacesIdNewsNewsIdRouteWithChildren =
  AdminWorkspacesIdNewsNewsIdRoute._addFileChildren(
    AdminWorkspacesIdNewsNewsIdRouteChildren,
  )

interface AdminWorkspacesIdRouteChildren {
  AdminWorkspacesIdAboutRoute: typeof AdminWorkspacesIdAboutRoute
  AdminWorkspacesIdAiAssistantRoute: typeof AdminWorkspacesIdAiAssistantRoute
  AdminWorkspacesIdAnalyticsRoute: typeof AdminWorkspacesIdAnalyticsRoute
  AdminWorkspacesIdApiExplorerRoute: typeof AdminWorkspacesIdApiExplorerRoute
  AdminWorkspacesIdApiKeysRoute: typeof AdminWorkspacesIdApiKeysRoute
  AdminWorkspacesIdArticlesRoute: typeof AdminWorkspacesIdArticlesRouteWithChildren
  AdminWorkspacesIdBlogsRoute: typeof AdminWorkspacesIdBlogsRouteWithChildren
  AdminWorkspacesIdCacheInvalidationRoute: typeof AdminWorkspacesIdCacheInvalidationRoute
  AdminWorkspacesIdCollectionsRoute: typeof AdminWorkspacesIdCollectionsRoute
  AdminWorkspacesIdCommentsRoute: typeof AdminWorkspacesIdCommentsRoute
  AdminWorkspacesIdDeveloperRoute: typeof AdminWorkspacesIdDeveloperRoute
  AdminWorkspacesIdIntegrationCenterRoute: typeof AdminWorkspacesIdIntegrationCenterRoute
  AdminWorkspacesIdMediaRoute: typeof AdminWorkspacesIdMediaRoute
  AdminWorkspacesIdNotificationsRoute: typeof AdminWorkspacesIdNotificationsRoute
  AdminWorkspacesIdProductsRoute: typeof AdminWorkspacesIdProductsRouteWithChildren
  AdminWorkspacesIdSettingsRoute: typeof AdminWorkspacesIdSettingsRoute
  AdminWorkspacesIdUsersRoute: typeof AdminWorkspacesIdUsersRoute
  AdminWorkspacesIdWebhooksRoute: typeof AdminWorkspacesIdWebhooksRoute
  AdminWorkspacesIdIndexRoute: typeof AdminWorkspacesIdIndexRoute
  AdminWorkspacesIdFaqsFaqIdRoute: typeof AdminWorkspacesIdFaqsFaqIdRouteWithChildren
  AdminWorkspacesIdFaqsNewRoute: typeof AdminWorkspacesIdFaqsNewRoute
  AdminWorkspacesIdNewsNewsIdRoute: typeof AdminWorkspacesIdNewsNewsIdRouteWithChildren
  AdminWorkspacesIdNewsNewRoute: typeof AdminWorkspacesIdNewsNewRoute
  AdminWorkspacesIdFaqsIndexRoute: typeof AdminWorkspacesIdFaqsIndexRoute
  AdminWorkspacesIdNewsIndexRoute: typeof AdminWorkspacesIdNewsIndexRoute
}

const AdminWorkspacesIdRouteChildren: AdminWorkspacesIdRouteChildren = {
  AdminWorkspacesIdAboutRoute: AdminWorkspacesIdAboutRoute,
  AdminWorkspacesIdAiAssistantRoute: AdminWorkspacesIdAiAssistantRoute,
  AdminWorkspacesIdAnalyticsRoute: AdminWorkspacesIdAnalyticsRoute,
  AdminWorkspacesIdApiExplorerRoute: AdminWorkspacesIdApiExplorerRoute,
  AdminWorkspacesIdApiKeysRoute: AdminWorkspacesIdApiKeysRoute,
  AdminWorkspacesIdArticlesRoute: AdminWorkspacesIdArticlesRouteWithChildren,
  AdminWorkspacesIdBlogsRoute: AdminWorkspacesIdBlogsRouteWithChildren,
  AdminWorkspacesIdCacheInvalidationRoute:
    AdminWorkspacesIdCacheInvalidationRoute,
  AdminWorkspacesIdCollectionsRoute: AdminWorkspacesIdCollectionsRoute,
  AdminWorkspacesIdCommentsRoute: AdminWorkspacesIdCommentsRoute,
  AdminWorkspacesIdDeveloperRoute: AdminWorkspacesIdDeveloperRoute,
  AdminWorkspacesIdIntegrationCenterRoute:
    AdminWorkspacesIdIntegrationCenterRoute,
  AdminWorkspacesIdMediaRoute: AdminWorkspacesIdMediaRoute,
  AdminWorkspacesIdNotificationsRoute: AdminWorkspacesIdNotificationsRoute,
  AdminWorkspacesIdProductsRoute: AdminWorkspacesIdProductsRouteWithChildren,
  AdminWorkspacesIdSettingsRoute: AdminWorkspacesIdSettingsRoute,
  AdminWorkspacesIdUsersRoute: AdminWorkspacesIdUsersRoute,
  AdminWorkspacesIdWebhooksRoute: AdminWorkspacesIdWebhooksRoute,
  AdminWorkspacesIdIndexRoute: AdminWorkspacesIdIndexRoute,
  AdminWorkspacesIdFaqsFaqIdRoute: AdminWorkspacesIdFaqsFaqIdRouteWithChildren,
  AdminWorkspacesIdFaqsNewRoute: AdminWorkspacesIdFaqsNewRoute,
  AdminWorkspacesIdNewsNewsIdRoute:
    AdminWorkspacesIdNewsNewsIdRouteWithChildren,
  AdminWorkspacesIdNewsNewRoute: AdminWorkspacesIdNewsNewRoute,
  AdminWorkspacesIdFaqsIndexRoute: AdminWorkspacesIdFaqsIndexRoute,
  AdminWorkspacesIdNewsIndexRoute: AdminWorkspacesIdNewsIndexRoute,
}

const AdminWorkspacesIdRouteWithChildren =
  AdminWorkspacesIdRoute._addFileChildren(AdminWorkspacesIdRouteChildren)

interface AdminWorkspacesRouteChildren {
  AdminWorkspacesIdRoute: typeof AdminWorkspacesIdRouteWithChildren
}

const AdminWorkspacesRouteChildren: AdminWorkspacesRouteChildren = {
  AdminWorkspacesIdRoute: AdminWorkspacesIdRouteWithChildren,
}

const AdminWorkspacesRouteWithChildren = AdminWorkspacesRoute._addFileChildren(
  AdminWorkspacesRouteChildren,
)

interface AdminRouteChildren {
  AdminAiAssistantRoute: typeof AdminAiAssistantRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiExplorerRoute: typeof AdminApiExplorerRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminApiLogsRoute: typeof AdminApiLogsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCollectionsRoute: typeof AdminCollectionsRouteWithChildren
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminIntegrationCenterRoute: typeof AdminIntegrationCenterRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogStatsPostIdRoute: typeof AdminBlogStatsPostIdRoute
  AdminBlogsIdRoute: typeof AdminBlogsIdRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiAssistantRoute: AdminAiAssistantRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiExplorerRoute: AdminApiExplorerRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminApiLogsRoute: AdminApiLogsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCollectionsRoute: AdminCollectionsRouteWithChildren,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminIntegrationCenterRoute: AdminIntegrationCenterRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminWorkspacesRoute: AdminWorkspacesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogStatsPostIdRoute: AdminBlogStatsPostIdRoute,
  AdminBlogsIdRoute: AdminBlogsIdRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAnalyzingRoute: typeof OnboardingAnalyzingRoute
  OnboardingCollectionsRoute: typeof OnboardingCollectionsRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingPreparingRoute: typeof OnboardingPreparingRoute
  OnboardingWebsiteRoute: typeof OnboardingWebsiteRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAnalyzingRoute: OnboardingAnalyzingRoute,
  OnboardingCollectionsRoute: OnboardingCollectionsRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingPreparingRoute: OnboardingPreparingRoute,
  OnboardingWebsiteRoute: OnboardingWebsiteRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignupRoute: SignupRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
