/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdminWorkspacesRouteImport } from './routes/admin.workspaces'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminApiExplorerRouteImport } from './routes/admin.api-explorer'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin.blogs.index'
import { Route as AdminCollectionsIdRouteImport } from './routes/admin.collections.$id'
import { Route as AdminBlogsNewRouteImport } from './routes/admin.blogs.new'
import { Route as AdminBlogsIdRouteImport } from './routes/admin.blogs.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiExplorerRoute = AdminApiExplorerRouteImport.update({
  id: '/api-explorer',
  path: '/api-explorer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsIdRoute = AdminCollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCollectionsRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIdRoute = AdminBlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/blogs/': typeof AdminBlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/admin/'
    | '/blogs/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/admin'
    | '/blogs'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/blogs'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/admin/'
    | '/blogs/'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-explorer': {
      id: '/admin/api-explorer'
      path: '/api-explorer'
      fullPath: '/admin/api-explorer'
      preLoaderRoute: typeof AdminApiExplorerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections/$id': {
      id: '/admin/collections/$id'
      path: '/$id'
      fullPath: '/admin/collections/$id'
      preLoaderRoute: typeof AdminCollectionsIdRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/$id': {
      id: '/admin/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminBlogsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminCollectionsRouteChildren {
  AdminCollectionsIdRoute: typeof AdminCollectionsIdRoute
}

const AdminCollectionsRouteChildren: AdminCollectionsRouteChildren = {
  AdminCollectionsIdRoute: AdminCollectionsIdRoute,
}

const AdminCollectionsRouteWithChildren =
  AdminCollectionsRoute._addFileChildren(AdminCollectionsRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiExplorerRoute: typeof AdminApiExplorerRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCollectionsRoute: typeof AdminCollectionsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogsIdRoute: typeof AdminBlogsIdRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiExplorerRoute: AdminApiExplorerRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCollectionsRoute: AdminCollectionsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminWorkspacesRoute: AdminWorkspacesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogsIdRoute: AdminBlogsIdRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
