/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingWebsiteRouteImport } from './routes/onboarding.website'
import { Route as OnboardingPreparingRouteImport } from './routes/onboarding.preparing'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as OnboardingCollectionsRouteImport } from './routes/onboarding.collections'
import { Route as OnboardingAnalyzingRouteImport } from './routes/onboarding.analyzing'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as AdminWorkspacesRouteImport } from './routes/admin.workspaces'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSearchRouteImport } from './routes/admin.search'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminApiLogsRouteImport } from './routes/admin.api-logs'
import { Route as AdminApiKeysRouteImport } from './routes/admin.api-keys'
import { Route as AdminApiExplorerRouteImport } from './routes/admin.api-explorer'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiAssistantRouteImport } from './routes/admin.ai-assistant'
import { Route as AdminBlogsIndexRouteImport } from './routes/admin.blogs.index'
import { Route as AdminWorkspacesIdRouteImport } from './routes/admin.workspaces.$id'
import { Route as AdminCollectionsIdRouteImport } from './routes/admin.collections.$id'
import { Route as AdminBlogsNewRouteImport } from './routes/admin.blogs.new'
import { Route as AdminBlogsIdRouteImport } from './routes/admin.blogs.$id'
import { Route as AdminBlogStatsPostIdRouteImport } from './routes/admin.blog-stats.$postId'
import { Route as AdminWorkspacesIdIndexRouteImport } from './routes/admin.workspaces.$id.index'
import { Route as AdminWorkspacesIdWebhooksRouteImport } from './routes/admin.workspaces.$id.webhooks'
import { Route as AdminWorkspacesIdUsersRouteImport } from './routes/admin.workspaces.$id.users'
import { Route as AdminWorkspacesIdSettingsRouteImport } from './routes/admin.workspaces.$id.settings'
import { Route as AdminWorkspacesIdNotificationsRouteImport } from './routes/admin.workspaces.$id.notifications'
import { Route as AdminWorkspacesIdMediaRouteImport } from './routes/admin.workspaces.$id.media'
import { Route as AdminWorkspacesIdIntegrationCenterRouteImport } from './routes/admin.workspaces.$id.integration-center'
import { Route as AdminWorkspacesIdCollectionsRouteImport } from './routes/admin.workspaces.$id.collections'
import { Route as AdminWorkspacesIdBlogsRouteImport } from './routes/admin.workspaces.$id.blogs'
import { Route as AdminWorkspacesIdApiKeysRouteImport } from './routes/admin.workspaces.$id.api-keys'
import { Route as AdminWorkspacesIdApiExplorerRouteImport } from './routes/admin.workspaces.$id.api-explorer'
import { Route as AdminWorkspacesIdAnalyticsRouteImport } from './routes/admin.workspaces.$id.analytics'
import { Route as AdminWorkspacesIdAiAssistantRouteImport } from './routes/admin.workspaces.$id.ai-assistant'
import { Route as AdminWorkspacesIdAboutRouteImport } from './routes/admin.workspaces.$id.about'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingWebsiteRoute = OnboardingWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPreparingRoute = OnboardingPreparingRouteImport.update({
  id: '/preparing',
  path: '/preparing',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCollectionsRoute = OnboardingCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAnalyzingRoute = OnboardingAnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => OnboardingRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/blogs/$slug',
  path: '/blogs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkspacesRoute = AdminWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiLogsRoute = AdminApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiExplorerRoute = AdminApiExplorerRouteImport.update({
  id: '/api-explorer',
  path: '/api-explorer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiAssistantRoute = AdminAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIndexRoute = AdminBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesIdRoute = AdminWorkspacesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminWorkspacesRoute,
} as any)
const AdminCollectionsIdRoute = AdminCollectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCollectionsRoute,
} as any)
const AdminBlogsNewRoute = AdminBlogsNewRouteImport.update({
  id: '/blogs/new',
  path: '/blogs/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsIdRoute = AdminBlogsIdRouteImport.update({
  id: '/blogs/$id',
  path: '/blogs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogStatsPostIdRoute = AdminBlogStatsPostIdRouteImport.update({
  id: '/blog-stats/$postId',
  path: '/blog-stats/$postId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorkspacesIdIndexRoute = AdminWorkspacesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdWebhooksRoute =
  AdminWorkspacesIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdUsersRoute = AdminWorkspacesIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdSettingsRoute =
  AdminWorkspacesIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdNotificationsRoute =
  AdminWorkspacesIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdMediaRoute = AdminWorkspacesIdMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdIntegrationCenterRoute =
  AdminWorkspacesIdIntegrationCenterRouteImport.update({
    id: '/integration-center',
    path: '/integration-center',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdCollectionsRoute =
  AdminWorkspacesIdCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdBlogsRoute = AdminWorkspacesIdBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)
const AdminWorkspacesIdApiKeysRoute =
  AdminWorkspacesIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdApiExplorerRoute =
  AdminWorkspacesIdApiExplorerRouteImport.update({
    id: '/api-explorer',
    path: '/api-explorer',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdAnalyticsRoute =
  AdminWorkspacesIdAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdAiAssistantRoute =
  AdminWorkspacesIdAiAssistantRouteImport.update({
    id: '/ai-assistant',
    path: '/ai-assistant',
    getParentRoute: () => AdminWorkspacesIdRoute,
  } as any)
const AdminWorkspacesIdAboutRoute = AdminWorkspacesIdAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminWorkspacesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/collections': typeof OnboardingCollectionsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/preparing': typeof OnboardingPreparingRoute
  '/onboarding/website': typeof OnboardingWebsiteRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/blog-stats/$postId': typeof AdminBlogStatsPostIdRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdRouteWithChildren
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/workspaces/$id/about': typeof AdminWorkspacesIdAboutRoute
  '/admin/workspaces/$id/ai-assistant': typeof AdminWorkspacesIdAiAssistantRoute
  '/admin/workspaces/$id/analytics': typeof AdminWorkspacesIdAnalyticsRoute
  '/admin/workspaces/$id/api-explorer': typeof AdminWorkspacesIdApiExplorerRoute
  '/admin/workspaces/$id/api-keys': typeof AdminWorkspacesIdApiKeysRoute
  '/admin/workspaces/$id/blogs': typeof AdminWorkspacesIdBlogsRoute
  '/admin/workspaces/$id/collections': typeof AdminWorkspacesIdCollectionsRoute
  '/admin/workspaces/$id/integration-center': typeof AdminWorkspacesIdIntegrationCenterRoute
  '/admin/workspaces/$id/media': typeof AdminWorkspacesIdMediaRoute
  '/admin/workspaces/$id/notifications': typeof AdminWorkspacesIdNotificationsRoute
  '/admin/workspaces/$id/settings': typeof AdminWorkspacesIdSettingsRoute
  '/admin/workspaces/$id/users': typeof AdminWorkspacesIdUsersRoute
  '/admin/workspaces/$id/webhooks': typeof AdminWorkspacesIdWebhooksRoute
  '/admin/workspaces/$id/': typeof AdminWorkspacesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/collections': typeof OnboardingCollectionsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/preparing': typeof OnboardingPreparingRoute
  '/onboarding/website': typeof OnboardingWebsiteRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin': typeof AdminIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/admin/blog-stats/$postId': typeof AdminBlogStatsPostIdRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/blogs': typeof AdminBlogsIndexRoute
  '/admin/workspaces/$id/about': typeof AdminWorkspacesIdAboutRoute
  '/admin/workspaces/$id/ai-assistant': typeof AdminWorkspacesIdAiAssistantRoute
  '/admin/workspaces/$id/analytics': typeof AdminWorkspacesIdAnalyticsRoute
  '/admin/workspaces/$id/api-explorer': typeof AdminWorkspacesIdApiExplorerRoute
  '/admin/workspaces/$id/api-keys': typeof AdminWorkspacesIdApiKeysRoute
  '/admin/workspaces/$id/blogs': typeof AdminWorkspacesIdBlogsRoute
  '/admin/workspaces/$id/collections': typeof AdminWorkspacesIdCollectionsRoute
  '/admin/workspaces/$id/integration-center': typeof AdminWorkspacesIdIntegrationCenterRoute
  '/admin/workspaces/$id/media': typeof AdminWorkspacesIdMediaRoute
  '/admin/workspaces/$id/notifications': typeof AdminWorkspacesIdNotificationsRoute
  '/admin/workspaces/$id/settings': typeof AdminWorkspacesIdSettingsRoute
  '/admin/workspaces/$id/users': typeof AdminWorkspacesIdUsersRoute
  '/admin/workspaces/$id/webhooks': typeof AdminWorkspacesIdWebhooksRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/ai-assistant': typeof AdminAiAssistantRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/api-explorer': typeof AdminApiExplorerRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/collections': typeof AdminCollectionsRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/search': typeof AdminSearchRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/workspaces': typeof AdminWorkspacesRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/onboarding/analyzing': typeof OnboardingAnalyzingRoute
  '/onboarding/collections': typeof OnboardingCollectionsRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/preparing': typeof OnboardingPreparingRoute
  '/onboarding/website': typeof OnboardingWebsiteRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/': typeof AdminIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/admin/blog-stats/$postId': typeof AdminBlogStatsPostIdRoute
  '/admin/blogs/$id': typeof AdminBlogsIdRoute
  '/admin/blogs/new': typeof AdminBlogsNewRoute
  '/admin/collections/$id': typeof AdminCollectionsIdRoute
  '/admin/workspaces/$id': typeof AdminWorkspacesIdRouteWithChildren
  '/admin/blogs/': typeof AdminBlogsIndexRoute
  '/admin/workspaces/$id/about': typeof AdminWorkspacesIdAboutRoute
  '/admin/workspaces/$id/ai-assistant': typeof AdminWorkspacesIdAiAssistantRoute
  '/admin/workspaces/$id/analytics': typeof AdminWorkspacesIdAnalyticsRoute
  '/admin/workspaces/$id/api-explorer': typeof AdminWorkspacesIdApiExplorerRoute
  '/admin/workspaces/$id/api-keys': typeof AdminWorkspacesIdApiKeysRoute
  '/admin/workspaces/$id/blogs': typeof AdminWorkspacesIdBlogsRoute
  '/admin/workspaces/$id/collections': typeof AdminWorkspacesIdCollectionsRoute
  '/admin/workspaces/$id/integration-center': typeof AdminWorkspacesIdIntegrationCenterRoute
  '/admin/workspaces/$id/media': typeof AdminWorkspacesIdMediaRoute
  '/admin/workspaces/$id/notifications': typeof AdminWorkspacesIdNotificationsRoute
  '/admin/workspaces/$id/settings': typeof AdminWorkspacesIdSettingsRoute
  '/admin/workspaces/$id/users': typeof AdminWorkspacesIdUsersRoute
  '/admin/workspaces/$id/webhooks': typeof AdminWorkspacesIdWebhooksRoute
  '/admin/workspaces/$id/': typeof AdminWorkspacesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/onboarding/analyzing'
    | '/onboarding/collections'
    | '/onboarding/complete'
    | '/onboarding/preparing'
    | '/onboarding/website'
    | '/onboarding/welcome'
    | '/admin/'
    | '/blogs/'
    | '/onboarding/'
    | '/admin/blog-stats/$postId'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/workspaces/$id'
    | '/admin/blogs/'
    | '/admin/workspaces/$id/about'
    | '/admin/workspaces/$id/ai-assistant'
    | '/admin/workspaces/$id/analytics'
    | '/admin/workspaces/$id/api-explorer'
    | '/admin/workspaces/$id/api-keys'
    | '/admin/workspaces/$id/blogs'
    | '/admin/workspaces/$id/collections'
    | '/admin/workspaces/$id/integration-center'
    | '/admin/workspaces/$id/media'
    | '/admin/workspaces/$id/notifications'
    | '/admin/workspaces/$id/settings'
    | '/admin/workspaces/$id/users'
    | '/admin/workspaces/$id/webhooks'
    | '/admin/workspaces/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/onboarding/analyzing'
    | '/onboarding/collections'
    | '/onboarding/complete'
    | '/onboarding/preparing'
    | '/onboarding/website'
    | '/onboarding/welcome'
    | '/admin'
    | '/blogs'
    | '/onboarding'
    | '/admin/blog-stats/$postId'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/blogs'
    | '/admin/workspaces/$id/about'
    | '/admin/workspaces/$id/ai-assistant'
    | '/admin/workspaces/$id/analytics'
    | '/admin/workspaces/$id/api-explorer'
    | '/admin/workspaces/$id/api-keys'
    | '/admin/workspaces/$id/blogs'
    | '/admin/workspaces/$id/collections'
    | '/admin/workspaces/$id/integration-center'
    | '/admin/workspaces/$id/media'
    | '/admin/workspaces/$id/notifications'
    | '/admin/workspaces/$id/settings'
    | '/admin/workspaces/$id/users'
    | '/admin/workspaces/$id/webhooks'
    | '/admin/workspaces/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/ai-assistant'
    | '/admin/analytics'
    | '/admin/api-explorer'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/billing'
    | '/admin/collections'
    | '/admin/dashboard'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/search'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/webhooks'
    | '/admin/workspaces'
    | '/blogs/$slug'
    | '/onboarding/analyzing'
    | '/onboarding/collections'
    | '/onboarding/complete'
    | '/onboarding/preparing'
    | '/onboarding/website'
    | '/onboarding/welcome'
    | '/admin/'
    | '/blogs/'
    | '/onboarding/'
    | '/admin/blog-stats/$postId'
    | '/admin/blogs/$id'
    | '/admin/blogs/new'
    | '/admin/collections/$id'
    | '/admin/workspaces/$id'
    | '/admin/blogs/'
    | '/admin/workspaces/$id/about'
    | '/admin/workspaces/$id/ai-assistant'
    | '/admin/workspaces/$id/analytics'
    | '/admin/workspaces/$id/api-explorer'
    | '/admin/workspaces/$id/api-keys'
    | '/admin/workspaces/$id/blogs'
    | '/admin/workspaces/$id/collections'
    | '/admin/workspaces/$id/integration-center'
    | '/admin/workspaces/$id/media'
    | '/admin/workspaces/$id/notifications'
    | '/admin/workspaces/$id/settings'
    | '/admin/workspaces/$id/users'
    | '/admin/workspaces/$id/webhooks'
    | '/admin/workspaces/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignupRoute: typeof SignupRoute
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/website': {
      id: '/onboarding/website'
      path: '/website'
      fullPath: '/onboarding/website'
      preLoaderRoute: typeof OnboardingWebsiteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/preparing': {
      id: '/onboarding/preparing'
      path: '/preparing'
      fullPath: '/onboarding/preparing'
      preLoaderRoute: typeof OnboardingPreparingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/collections': {
      id: '/onboarding/collections'
      path: '/collections'
      fullPath: '/onboarding/collections'
      preLoaderRoute: typeof OnboardingCollectionsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/analyzing': {
      id: '/onboarding/analyzing'
      path: '/analyzing'
      fullPath: '/onboarding/analyzing'
      preLoaderRoute: typeof OnboardingAnalyzingRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/blogs/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/workspaces': {
      id: '/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AdminWorkspacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/search': {
      id: '/admin/search'
      path: '/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-logs': {
      id: '/admin/api-logs'
      path: '/api-logs'
      fullPath: '/admin/api-logs'
      preLoaderRoute: typeof AdminApiLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-explorer': {
      id: '/admin/api-explorer'
      path: '/api-explorer'
      fullPath: '/admin/api-explorer'
      preLoaderRoute: typeof AdminApiExplorerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-assistant': {
      id: '/admin/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/admin/ai-assistant'
      preLoaderRoute: typeof AdminAiAssistantRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/': {
      id: '/admin/blogs/'
      path: '/blogs'
      fullPath: '/admin/blogs/'
      preLoaderRoute: typeof AdminBlogsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces/$id': {
      id: '/admin/workspaces/$id'
      path: '/$id'
      fullPath: '/admin/workspaces/$id'
      preLoaderRoute: typeof AdminWorkspacesIdRouteImport
      parentRoute: typeof AdminWorkspacesRoute
    }
    '/admin/collections/$id': {
      id: '/admin/collections/$id'
      path: '/$id'
      fullPath: '/admin/collections/$id'
      preLoaderRoute: typeof AdminCollectionsIdRouteImport
      parentRoute: typeof AdminCollectionsRoute
    }
    '/admin/blogs/new': {
      id: '/admin/blogs/new'
      path: '/blogs/new'
      fullPath: '/admin/blogs/new'
      preLoaderRoute: typeof AdminBlogsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs/$id': {
      id: '/admin/blogs/$id'
      path: '/blogs/$id'
      fullPath: '/admin/blogs/$id'
      preLoaderRoute: typeof AdminBlogsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-stats/$postId': {
      id: '/admin/blog-stats/$postId'
      path: '/blog-stats/$postId'
      fullPath: '/admin/blog-stats/$postId'
      preLoaderRoute: typeof AdminBlogStatsPostIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/workspaces/$id/': {
      id: '/admin/workspaces/$id/'
      path: '/'
      fullPath: '/admin/workspaces/$id/'
      preLoaderRoute: typeof AdminWorkspacesIdIndexRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/webhooks': {
      id: '/admin/workspaces/$id/webhooks'
      path: '/webhooks'
      fullPath: '/admin/workspaces/$id/webhooks'
      preLoaderRoute: typeof AdminWorkspacesIdWebhooksRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/users': {
      id: '/admin/workspaces/$id/users'
      path: '/users'
      fullPath: '/admin/workspaces/$id/users'
      preLoaderRoute: typeof AdminWorkspacesIdUsersRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/settings': {
      id: '/admin/workspaces/$id/settings'
      path: '/settings'
      fullPath: '/admin/workspaces/$id/settings'
      preLoaderRoute: typeof AdminWorkspacesIdSettingsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/notifications': {
      id: '/admin/workspaces/$id/notifications'
      path: '/notifications'
      fullPath: '/admin/workspaces/$id/notifications'
      preLoaderRoute: typeof AdminWorkspacesIdNotificationsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/media': {
      id: '/admin/workspaces/$id/media'
      path: '/media'
      fullPath: '/admin/workspaces/$id/media'
      preLoaderRoute: typeof AdminWorkspacesIdMediaRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/integration-center': {
      id: '/admin/workspaces/$id/integration-center'
      path: '/integration-center'
      fullPath: '/admin/workspaces/$id/integration-center'
      preLoaderRoute: typeof AdminWorkspacesIdIntegrationCenterRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/collections': {
      id: '/admin/workspaces/$id/collections'
      path: '/collections'
      fullPath: '/admin/workspaces/$id/collections'
      preLoaderRoute: typeof AdminWorkspacesIdCollectionsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/blogs': {
      id: '/admin/workspaces/$id/blogs'
      path: '/blogs'
      fullPath: '/admin/workspaces/$id/blogs'
      preLoaderRoute: typeof AdminWorkspacesIdBlogsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/api-keys': {
      id: '/admin/workspaces/$id/api-keys'
      path: '/api-keys'
      fullPath: '/admin/workspaces/$id/api-keys'
      preLoaderRoute: typeof AdminWorkspacesIdApiKeysRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/api-explorer': {
      id: '/admin/workspaces/$id/api-explorer'
      path: '/api-explorer'
      fullPath: '/admin/workspaces/$id/api-explorer'
      preLoaderRoute: typeof AdminWorkspacesIdApiExplorerRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/analytics': {
      id: '/admin/workspaces/$id/analytics'
      path: '/analytics'
      fullPath: '/admin/workspaces/$id/analytics'
      preLoaderRoute: typeof AdminWorkspacesIdAnalyticsRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/ai-assistant': {
      id: '/admin/workspaces/$id/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/admin/workspaces/$id/ai-assistant'
      preLoaderRoute: typeof AdminWorkspacesIdAiAssistantRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
    '/admin/workspaces/$id/about': {
      id: '/admin/workspaces/$id/about'
      path: '/about'
      fullPath: '/admin/workspaces/$id/about'
      preLoaderRoute: typeof AdminWorkspacesIdAboutRouteImport
      parentRoute: typeof AdminWorkspacesIdRoute
    }
  }
}

interface AdminCollectionsRouteChildren {
  AdminCollectionsIdRoute: typeof AdminCollectionsIdRoute
}

const AdminCollectionsRouteChildren: AdminCollectionsRouteChildren = {
  AdminCollectionsIdRoute: AdminCollectionsIdRoute,
}

const AdminCollectionsRouteWithChildren =
  AdminCollectionsRoute._addFileChildren(AdminCollectionsRouteChildren)

interface AdminWorkspacesIdRouteChildren {
  AdminWorkspacesIdAboutRoute: typeof AdminWorkspacesIdAboutRoute
  AdminWorkspacesIdAiAssistantRoute: typeof AdminWorkspacesIdAiAssistantRoute
  AdminWorkspacesIdAnalyticsRoute: typeof AdminWorkspacesIdAnalyticsRoute
  AdminWorkspacesIdApiExplorerRoute: typeof AdminWorkspacesIdApiExplorerRoute
  AdminWorkspacesIdApiKeysRoute: typeof AdminWorkspacesIdApiKeysRoute
  AdminWorkspacesIdBlogsRoute: typeof AdminWorkspacesIdBlogsRoute
  AdminWorkspacesIdCollectionsRoute: typeof AdminWorkspacesIdCollectionsRoute
  AdminWorkspacesIdIntegrationCenterRoute: typeof AdminWorkspacesIdIntegrationCenterRoute
  AdminWorkspacesIdMediaRoute: typeof AdminWorkspacesIdMediaRoute
  AdminWorkspacesIdNotificationsRoute: typeof AdminWorkspacesIdNotificationsRoute
  AdminWorkspacesIdSettingsRoute: typeof AdminWorkspacesIdSettingsRoute
  AdminWorkspacesIdUsersRoute: typeof AdminWorkspacesIdUsersRoute
  AdminWorkspacesIdWebhooksRoute: typeof AdminWorkspacesIdWebhooksRoute
  AdminWorkspacesIdIndexRoute: typeof AdminWorkspacesIdIndexRoute
}

const AdminWorkspacesIdRouteChildren: AdminWorkspacesIdRouteChildren = {
  AdminWorkspacesIdAboutRoute: AdminWorkspacesIdAboutRoute,
  AdminWorkspacesIdAiAssistantRoute: AdminWorkspacesIdAiAssistantRoute,
  AdminWorkspacesIdAnalyticsRoute: AdminWorkspacesIdAnalyticsRoute,
  AdminWorkspacesIdApiExplorerRoute: AdminWorkspacesIdApiExplorerRoute,
  AdminWorkspacesIdApiKeysRoute: AdminWorkspacesIdApiKeysRoute,
  AdminWorkspacesIdBlogsRoute: AdminWorkspacesIdBlogsRoute,
  AdminWorkspacesIdCollectionsRoute: AdminWorkspacesIdCollectionsRoute,
  AdminWorkspacesIdIntegrationCenterRoute:
    AdminWorkspacesIdIntegrationCenterRoute,
  AdminWorkspacesIdMediaRoute: AdminWorkspacesIdMediaRoute,
  AdminWorkspacesIdNotificationsRoute: AdminWorkspacesIdNotificationsRoute,
  AdminWorkspacesIdSettingsRoute: AdminWorkspacesIdSettingsRoute,
  AdminWorkspacesIdUsersRoute: AdminWorkspacesIdUsersRoute,
  AdminWorkspacesIdWebhooksRoute: AdminWorkspacesIdWebhooksRoute,
  AdminWorkspacesIdIndexRoute: AdminWorkspacesIdIndexRoute,
}

const AdminWorkspacesIdRouteWithChildren =
  AdminWorkspacesIdRoute._addFileChildren(AdminWorkspacesIdRouteChildren)

interface AdminWorkspacesRouteChildren {
  AdminWorkspacesIdRoute: typeof AdminWorkspacesIdRouteWithChildren
}

const AdminWorkspacesRouteChildren: AdminWorkspacesRouteChildren = {
  AdminWorkspacesIdRoute: AdminWorkspacesIdRouteWithChildren,
}

const AdminWorkspacesRouteWithChildren = AdminWorkspacesRoute._addFileChildren(
  AdminWorkspacesRouteChildren,
)

interface AdminRouteChildren {
  AdminAiAssistantRoute: typeof AdminAiAssistantRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApiExplorerRoute: typeof AdminApiExplorerRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminApiLogsRoute: typeof AdminApiLogsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCollectionsRoute: typeof AdminCollectionsRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminWorkspacesRoute: typeof AdminWorkspacesRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogStatsPostIdRoute: typeof AdminBlogStatsPostIdRoute
  AdminBlogsIdRoute: typeof AdminBlogsIdRoute
  AdminBlogsNewRoute: typeof AdminBlogsNewRoute
  AdminBlogsIndexRoute: typeof AdminBlogsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiAssistantRoute: AdminAiAssistantRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApiExplorerRoute: AdminApiExplorerRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminApiLogsRoute: AdminApiLogsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCollectionsRoute: AdminCollectionsRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminWorkspacesRoute: AdminWorkspacesRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogStatsPostIdRoute: AdminBlogStatsPostIdRoute,
  AdminBlogsIdRoute: AdminBlogsIdRoute,
  AdminBlogsNewRoute: AdminBlogsNewRoute,
  AdminBlogsIndexRoute: AdminBlogsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OnboardingRouteChildren {
  OnboardingAnalyzingRoute: typeof OnboardingAnalyzingRoute
  OnboardingCollectionsRoute: typeof OnboardingCollectionsRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingPreparingRoute: typeof OnboardingPreparingRoute
  OnboardingWebsiteRoute: typeof OnboardingWebsiteRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAnalyzingRoute: OnboardingAnalyzingRoute,
  OnboardingCollectionsRoute: OnboardingCollectionsRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingPreparingRoute: OnboardingPreparingRoute,
  OnboardingWebsiteRoute: OnboardingWebsiteRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignupRoute: SignupRoute,
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
