// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzhsjhprnqfhixjkekxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6aHNqaHBybnFmaGl4amtla3hyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI4OTM3NTcsImV4cCI6MjA5ODQ2OTc1N30.flSQMwCClwti_jw8ab3cAjoKkaZ-qowYz0lT4xllZyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});